# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 0 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: tmchuynh
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          base: metadata
          commits_authoring: tmchuynh
          extras_css: |
            .field svg {
              fill: #004ba3;
            }
            .field {
              color: #801118;
            }
              h1, h2, h3, a {
                 color: #fff !important;
            }
          extras_js: |
            for (const {a, b} of [
              {a:"#216e39", b:"#801118"},
              {a:"#30a14e", b:"#a1242c"},
              {a:"#40c463", b:"#cc4952"},
              {a:"#9be9a8", b:"#fcaf93"},
              {a:"#ebedf0", b:"#fee2d5"},
            ])
            document.querySelectorAll(`svg g [fill="${a}"]`).forEach(node => node.setAttribute("fill", b))
          config_octicon: yes
          config_order: base.header, introduction, isocalendar, languages, code, activity, habits, habits_fact, habits_charts, lines, people, achievements, posts, stars
          config_timezone: America/Los_Angeles
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_days: 7
          plugin_code_lines: 12
          plugin_code_load: 400
          plugin_code_skipped: css, html
          plugin_code_visibility: all
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_days: 7
          plugin_habits_from: 1000
          plugin_habits_charts_type: chartist
          plugin_habits_trim: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 100
          plugin_people_size: 15
          plugin_people_types: followers, following
          plugin_posts: yes
          plugin_posts_limit: 10
          plugin_posts_source: dev.to
          plugin_posts_user: tmchuynh
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_topics_mode: icons
